### ISSUE TITLE
Update summary description of Club.

### ISSUE THREAD

**Issue by rchampieux** [daniellecrobinson/OHSU-Code-Club#14]
Update description of club to:

OHSU Code Club is an informal, on-campus meetup initiated by a group of OHSU students, staff, and faculty. We come together to share skills, ask questions, and learn new open research tools. We believe anyone can learn to program and are happy to help you start from scratch! Join us to write your first line of code, learn new data management and analysis skills, try your hand at teaching in an informal context - or just show up at our Hacky Hour Co-working events to work on your own projects with company.

**Comment by daniellecrobinson** [comment]
Done!
