### ISSUE TITLE
Add Data Jamboree to friends and resources

### ISSUE THREAD

**Issue by rchampieux** [daniellecrobinson/OHSU-Code-Club#15]
Short description of "friend":

Organized by OHSU Computational Biology in the School of Medicine, the monthly Data Jamboree series provides interactive lectures, hands-on workshops, and community building related to data science research and learning.

Data Jamboree link:  https://www.ohsu.edu/xd/education/schools/school-of-medicine/departments/computational-biology/events/data-jamboree.cfm

**Comment by daniellecrobinson** [comment]
Added them!
