### ISSUE TITLE
I broke the calendar...sorry!

### ISSUE THREAD

**Issue by laderast** [daniellecrobinson/OHSU-Code-Club#39]
Hi Danielle,

I was just editing the YML for the tidyverse post and somehow it messed up the calendar display. Can you just revert to before I committed the change and see if that fixes it?

**Comment by erictleung** [comment]
@laderast I think the YAML header is very colon sensitive so that might be breaking it.

**Comment by laderast** [comment]
Ok. I will merge when I'm back at my desk
